module.exports = {
  Aveiro: [
    { cod: 101, nome: "Águeda", distrito: 1 },
    { cod: 102, nome: "Albergaria-a-Velha", distrito: 1 },
    { cod: 103, nome: "Anadia", distrito: 1 },
    { cod: 104, nome: "Arouca", distrito: 1 },
    { cod: 105, nome: "Aveiro", distrito: 1 },
    { cod: 106, nome: "Castelo de Paiva", distrito: 1 },
    { cod: 107, nome: "Espinho", distrito: 1 },
    { cod: 108, nome: "Estarreja", distrito: 1 },
    { cod: 109, nome: "Ílhavo", distrito: 1 },
    { cod: 110, nome: "Mealhada", distrito: 1 },
    { cod: 111, nome: "Murtosa", distrito: 1 },
    { cod: 112, nome: "Oliveira de Azeméis", distrito: 1 },
    { cod: 113, nome: "Oliveira do Bairro", distrito: 1 },
    { cod: 114, nome: "Ovar", distrito: 1 },
    { cod: 115, nome: "Santa Maria da Feira", distrito: 1 },
    { cod: 116, nome: "São João da Madeira", distrito: 1 },
    { cod: 117, nome: "Sever do Vouga", distrito: 1 },
    { cod: 118, nome: "Vagos", distrito: 1 },
    { cod: 119, nome: "Vale de Cambra", distrito: 1 },
  ],
  Beja: [
    { cod: 201, nome: "Aljustrel", distrito: 2 },
    { cod: 202, nome: "Almodôvar", distrito: 2 },
    { cod: 203, nome: "Alvito", distrito: 2 },
    { cod: 204, nome: "Barrancos", distrito: 2 },
    { cod: 205, nome: "Beja", distrito: 2 },
    { cod: 206, nome: "Castro Verde", distrito: 2 },
    { cod: 207, nome: "Cuba", distrito: 2 },
    { cod: 208, nome: "Ferreira do Alentejo", distrito: 2 },
    { cod: 209, nome: "Mértola", distrito: 2 },
    { cod: 210, nome: "Moura", distrito: 2 },
    { cod: 211, nome: "Odemira", distrito: 2 },
    { cod: 212, nome: "Ourique", distrito: 2 },
    { cod: 213, nome: "Serpa", distrito: 2 },
    { cod: 214, nome: "Vidigueira", distrito: 2 },
  ],
  Braga: [
    { cod: 301, nome: "Amares", distrito: 3 },
    { cod: 302, nome: "Barcelos", distrito: 3 },
    { cod: 303, nome: "Braga", distrito: 3 },
    { cod: 304, nome: "Cabeceiras de Basto", distrito: 3 },
    { cod: 305, nome: "Celorico de Basto", distrito: 3 },
    { cod: 306, nome: "Esposende", distrito: 3 },
    { cod: 307, nome: "Fafe", distrito: 3 },
    { cod: 308, nome: "Guimarães", distrito: 3 },
    { cod: 309, nome: "Póvoa do Lanhoso", distrito: 3 },
    { cod: 310, nome: "Terras de Bouro", distrito: 3 },
    { cod: 311, nome: "Vieira do Minho", distrito: 3 },
    {
      cod: 312,
      nome: "Vila Nova de Famalicão",
      distrito: 3,
    },
    { cod: 313, nome: "Vila Verde", distrito: 3 },
    { cod: 314, nome: "Vizela", distrito: 3 },
  ],
  Bragança: [
    { cod: 401, nome: "Alfândega da Fé", distrito: 4 },
    { cod: 402, nome: "Bragança", distrito: 4 },
    { cod: 403, nome: "Carrazeda de Ansiães", distrito: 4 },
    {
      cod: 404,
      nome: "Freixo de Espada à Cinta",
      distrito: 4,
    },
    { cod: 405, nome: "Macedo de Cavaleiros", distrito: 4 },
    { cod: 406, nome: "Miranda do Douro", distrito: 4 },
    { cod: 407, nome: "Mirandela", distrito: 4 },
    { cod: 408, nome: "Mogadouro", distrito: 4 },
    { cod: 409, nome: "Torre de Moncorvo", distrito: 4 },
    { cod: 410, nome: "Vila de Flor", distrito: 4 },
    { cod: 411, nome: "Vimioso", distrito: 4 },
    { cod: 412, nome: "Vinhais", distrito: 4 },
  ],
  "Castelo Branco": [
    { cod: 501, nome: "Belmonte", distrito: 5 },
    { cod: 502, nome: "Castelo Branco", distrito: 5 },
    { cod: 503, nome: "Covilhã", distrito: 5 },
    { cod: 504, nome: "Fundão", distrito: 5 },
    { cod: 505, nome: "Idanha-a-Nova", distrito: 5 },
    { cod: 506, nome: "Oleiros", distrito: 5 },
    { cod: 507, nome: "Penamancor", distrito: 5 },
    { cod: 508, nome: "Proença-a-Nova", distrito: 5 },
    { cod: 509, nome: "Sertã", distrito: 5 },
    { cod: 510, nome: "Vila de Rei", distrito: 5 },
    { cod: 511, nome: "Vila Velha de Rodão", distrito: 5 },
  ],
  Coimbra: [
    { cod: 601, nome: "Arganil", distrito: 6 },
    { cod: 602, nome: "Cantanhede", distrito: 6 },
    { cod: 603, nome: "Coimbra", distrito: 6 },
    { cod: 604, nome: "Condeixa-a-Nova", distrito: 6 },
    { cod: 605, nome: "Figueira da Foz", distrito: 6 },
    { cod: 606, nome: "Góis", distrito: 6 },
    { cod: 607, nome: "Lousã", distrito: 6 },
    { cod: 608, nome: "Mira", distrito: 6 },
    { cod: 609, nome: "Miranda do Corvo", distrito: 6 },
    { cod: 610, nome: "Montemor-o-Velho", distrito: 6 },
    { cod: 611, nome: "Oliveira do Hospital", distrito: 6 },
    { cod: 612, nome: "Pampilhosa da Serra", distrito: 6 },
    { cod: 613, nome: "Penacova", distrito: 6 },
    { cod: 614, nome: "Penela", distrito: 6 },
    { cod: 615, nome: "Soure", distrito: 6 },
    { cod: 616, nome: "Tábua", distrito: 6 },
    { cod: 617, nome: "Vila Nova de Poiares", distrito: 6 },
  ],
  Évora: [
    { cod: 701, nome: "Alandroal", distrito: 7 },
    { cod: 702, nome: "Arraiolos", distrito: 7 },
    { cod: 703, nome: "Borba", distrito: 7 },
    { cod: 704, nome: "Estremoz", distrito: 7 },
    { cod: 705, nome: "Évora", distrito: 7 },
    { cod: 706, nome: "Montemor-o-Novo", distrito: 7 },
    { cod: 707, nome: "Mora", distrito: 7 },
    { cod: 708, nome: "Mourão", distrito: 7 },
    { cod: 709, nome: "Portel", distrito: 7 },
    { cod: 710, nome: "Redondo", distrito: 7 },
    {
      cod: 711,
      nome: "Reguengos de Monsaraz",
      distrito: 7,
    },
    { cod: 712, nome: "Vendas Novas", distrito: 7 },
    { cod: 713, nome: "Viana do Alentejo", distrito: 7 },
    { cod: 714, nome: "Vila Viçosa", distrito: 7 },
  ],
  Faro: [
    { cod: 801, nome: "Albufeira", distrito: 8 },
    { cod: 802, nome: "Alcoutim", distrito: 8 },
    { cod: 803, nome: "Aljezur", distrito: 8 },
    { cod: 804, nome: "Castro Marim", distrito: 8 },
    { cod: 805, nome: "Faro", distrito: 8 },
    { cod: 806, nome: "Lagoa", distrito: 8 },
    { cod: 807, nome: "Lagos", distrito: 8 },
    { cod: 808, nome: "Loulé", distrito: 8 },
    { cod: 809, nome: "Monchique", distrito: 8 },
    { cod: 810, nome: "Olhão", distrito: 8 },
    { cod: 811, nome: "Portimão", distrito: 8 },
    { cod: 812, nome: "São Brás de Alportel", distrito: 8 },
    { cod: 813, nome: "Silves", distrito: 8 },
    { cod: 814, nome: "Tavira", distrito: 8 },
    { cod: 815, nome: "Vila do Bispo", distrito: 8 },
    {
      cod: 816,
      nome: "Vila Real de Santo António",
      distrito: 8,
    },
  ],
  Guarda: [
    { cod: 901, nome: "Aguiar da Beira", distrito: 9 },
    { cod: 902, nome: "Almeida", distrito: 9 },
    { cod: 903, nome: "Celorico da Beira", distrito: 9 },
    {
      cod: 904,
      nome: "Figueira de Castelo Rodrigo",
      distrito: 9,
    },
    { cod: 905, nome: "Fornos de Algodres", distrito: 9 },
    { cod: 906, nome: "Gouveia", distrito: 9 },
    { cod: 907, nome: "Guarda", distrito: 9 },
    { cod: 908, nome: "Manteigas", distrito: 9 },
    { cod: 909, nome: "Mêda", distrito: 9 },
    { cod: 910, nome: "Pinhel", distrito: 9 },
    { cod: 911, nome: "Sabugal", distrito: 9 },
    { cod: 912, nome: "Seia", distrito: 9 },
    { cod: 913, nome: "Trancoso", distrito: 9 },
    { cod: 914, nome: "Vila Nova de Foz Côa", distrito: 9 },
  ],
  Leiria: [
    { cod: 1001, nome: "Alcobaça", distrito: 10 },
    { cod: 1002, nome: "Alvaiázere", distrito: 10 },
    { cod: 1003, nome: "Ansião", distrito: 10 },
    { cod: 1004, nome: "Batalha", distrito: 10 },
    { cod: 1005, nome: "Bombarral", distrito: 10 },
    { cod: 1006, nome: "Caldas da Rainha", distrito: 10 },
    {
      cod: 1007,
      nome: "Castanheira de Pêra",
      distrito: 10,
    },
    {
      cod: 1008,
      nome: "Figueiró dos Vinhos",
      distrito: 10,
    },
    { cod: 1009, nome: "Leiria", distrito: 10 },
    { cod: 1010, nome: "Marinha Grande", distrito: 10 },
    { cod: 1011, nome: "Nazaré", distrito: 10 },
    { cod: 1012, nome: "Óbidos", distrito: 10 },
    { cod: 1013, nome: "Pedrógão Grande", distrito: 10 },
    { cod: 1014, nome: "Peniche", distrito: 10 },
    { cod: 1015, nome: "Pombal", distrito: 10 },
    { cod: 1016, nome: "Porto de Mós", distrito: 10 },
  ],
  Lisboa: [
    { cod: 1101, nome: "Alenquer", distrito: 11 },
    { cod: 1102, nome: "Amadora", distrito: 11 },
    { cod: 1103, nome: "Arruda dos Vinhos", distrito: 11 },
    { cod: 1104, nome: "Azambuja", distrito: 11 },
    { cod: 1105, nome: "Cadaval", distrito: 11 },
    { cod: 1106, nome: "Cascais", distrito: 11 },
    { cod: 1107, nome: "Lisboa", distrito: 11 },
    { cod: 1108, nome: "Loures", distrito: 11 },
    { cod: 1109, nome: "Lourinhã", distrito: 11 },
    { cod: 1110, nome: "Mafra", distrito: 11 },
    { cod: 1111, nome: "Odivelas", distrito: 11 },
    { cod: 1112, nome: "Oeiras", distrito: 11 },
    { cod: 1113, nome: "Sintra", distrito: 11 },
    {
      cod: 1114,
      nome: "Sobral de Monte Agraço",
      distrito: 11,
    },
    { cod: 1115, nome: "Torres Vedras", distrito: 11 },
    {
      cod: 1116,
      nome: "Vila Franca de Xira",
      distrito: 11,
    },
  ],
  Portalegre: [
    { cod: 1201, nome: "Elvas", distrito: 12 },
    { cod: 1202, nome: "Portalegre", distrito: 12 },
    { cod: 1203, nome: "Ponte de Sôr", distrito: 12 },
    { cod: 1204, nome: "Campo Maior", distrito: 12 },
    { cod: 1205, nome: "Nisa", distrito: 12 },
    { cod: 1206, nome: "Alter do Chão", distrito: 12 },
    { cod: 1207, nome: "Castelo de Vide", distrito: 12 },
    { cod: 1208, nome: "Fronteira", distrito: 12 },
    { cod: 1209, nome: "Arronches", distrito: 12 },
    { cod: 1210, nome: "Sousel", distrito: 12 },
    { cod: 1211, nome: "Avis", distrito: 12 },
    { cod: 1212, nome: "Crato", distrito: 12 },
    { cod: 1213, nome: "Gavião", distrito: 12 },
    { cod: 1214, nome: "Monforte", distrito: 12 },
    { cod: 1215, nome: "Marvão", distrito: 12 },
  ],
  Porto: [
    { cod: 1301, nome: "Amarante", distrito: 13 },
    { cod: 1302, nome: "Baião", distrito: 13 },
    { cod: 1303, nome: "Felgueiras", distrito: 13 },
    { cod: 1304, nome: "Gondomar", distrito: 13 },
    { cod: 1305, nome: "Lousada", distrito: 13 },
    { cod: 1306, nome: "Maia", distrito: 13 },
    { cod: 1307, nome: "Marco de Canaveses", distrito: 13 },
    { cod: 1308, nome: "Matosinhos", distrito: 13 },
    { cod: 1309, nome: "Paços de Ferreira", distrito: 13 },
    { cod: 1310, nome: "Paredes", distrito: 13 },
    { cod: 1311, nome: "Penafiel", distrito: 13 },
    { cod: 1312, nome: "Porto", distrito: 13 },
    { cod: 1313, nome: "Póvoa do Varzim", distrito: 13 },
    { cod: 1314, nome: "Santo Tirso", distrito: 13 },
    { cod: 1315, nome: "Trofa", distrito: 13 },
    { cod: 1316, nome: "Valongo", distrito: 13 },
    { cod: 1317, nome: "Vila do Conde", distrito: 13 },
    { cod: 1318, nome: "Vila Nova de Gaia", distrito: 13 },
  ],
  Santarém: [
    { cod: 1401, nome: "Abrantes", distrito: 14 },
    { cod: 1402, nome: "Alcanena", distrito: 14 },
    { cod: 1403, nome: "Almeirim", distrito: 14 },
    { cod: 1404, nome: "Alpiarça", distrito: 14 },
    { cod: 1405, nome: "Benavente", distrito: 14 },
    { cod: 1406, nome: "Cartaxo", distrito: 14 },
    { cod: 1407, nome: "Chamusca", distrito: 14 },
    { cod: 1408, nome: "Constância", distrito: 14 },
    { cod: 1409, nome: "Coruche", distrito: 14 },
    { cod: 1410, nome: "Entroncamento", distrito: 14 },
    { cod: 1411, nome: "Ferreira do Zêzere", distrito: 14 },
    { cod: 1412, nome: "Golegã", distrito: 14 },
    { cod: 1413, nome: "Mação", distrito: 14 },
    { cod: 1414, nome: "Ourém", distrito: 14 },
    { cod: 1415, nome: "Rio Maior", distrito: 14 },
    {
      cod: 1416,
      nome: "Salvaterra de Magos",
      distrito: 14,
    },
    { cod: 1417, nome: "Santarém", distrito: 14 },
    { cod: 1418, nome: "Sardoal", distrito: 14 },
    { cod: 1419, nome: "Tomar", distrito: 14 },
    { cod: 1420, nome: "Torres Novas", distrito: 14 },
    {
      cod: 1421,
      nome: "Vila Nova da Barquinha",
      distrito: 14,
    },
  ],
  Setúbal: [
    { cod: 1501, nome: "Alcácer do Sal", distrito: 15 },
    { cod: 1502, nome: "Alcochete", distrito: 15 },
    { cod: 1503, nome: "Almada", distrito: 15 },
    { cod: 1504, nome: "Barreiro", distrito: 15 },
    { cod: 1505, nome: "Grândola", distrito: 15 },
    { cod: 1506, nome: "Moita", distrito: 15 },
    { cod: 1507, nome: "Montijo", distrito: 15 },
    { cod: 1508, nome: "Palmela", distrito: 15 },
    { cod: 1509, nome: "Santiago do Cacém", distrito: 15 },
    { cod: 1510, nome: "Seixal", distrito: 15 },
    { cod: 1511, nome: "Sesimbra", distrito: 15 },
    { cod: 1512, nome: "Setúbal", distrito: 15 },
    { cod: 1513, nome: "Sines", distrito: 15 },
  ],
  "Viana do Castelo": [
    { cod: 1601, nome: "Arcos de Valdevez", distrito: 16 },
    { cod: 1602, nome: "Caminha", distrito: 16 },
    { cod: 1603, nome: "Melgaço", distrito: 16 },
    { cod: 1604, nome: "Monção", distrito: 16 },
    { cod: 1605, nome: "Paredes de Coura", distrito: 16 },
    { cod: 1606, nome: "Ponte de Barca", distrito: 16 },
    { cod: 1607, nome: "Ponte de Lima", distrito: 16 },
    { cod: 1608, nome: "Valença", distrito: 16 },
    { cod: 1609, nome: "Viana do Castelo", distrito: 16 },
    {
      cod: 1610,
      nome: "Vila Nova de Cerveira",
      distrito: 16,
    },
  ],
  "Vila Real": [
    { cod: 1701, nome: "Alijó", distrito: 17 },
    { cod: 1702, nome: "Boticas", distrito: 17 },
    { cod: 1703, nome: "Chaves", distrito: 17 },
    { cod: 1704, nome: "Mesão Frio", distrito: 17 },
    { cod: 1705, nome: "Mondim de Basto", distrito: 17 },
    { cod: 1706, nome: "Montalegre", distrito: 17 },
    { cod: 1707, nome: "Murça", distrito: 17 },
    { cod: 1708, nome: "Peso da Régua", distrito: 17 },
    { cod: 1709, nome: "Ribeira de Pena", distrito: 17 },
    { cod: 1710, nome: "Sabrosa", distrito: 17 },
    {
      cod: 1711,
      nome: "Santa Marta de Penaguião",
      distrito: 17,
    },
    { cod: 1712, nome: "Valpaços", distrito: 17 },
    {
      cod: 1713,
      nome: "Vila Pouca de Aguiar",
      distrito: 17,
    },
    { cod: 1714, nome: "Vila Real", distrito: 17 },
  ],
  Viseu: [
    { cod: 1801, nome: "Armamar", distrito: 18 },
    { cod: 1802, nome: "Carregal do Sal", distrito: 18 },
    { cod: 1803, nome: "Castro Daire", distrito: 18 },
    { cod: 1804, nome: "Cinfães", distrito: 18 },
    { cod: 1805, nome: "Lamego", distrito: 18 },
    { cod: 1806, nome: "Mangualde", distrito: 18 },
    { cod: 1807, nome: "Moimenta da Beira", distrito: 18 },
    { cod: 1808, nome: "Mortágua", distrito: 18 },
    { cod: 1809, nome: "Nelas", distrito: 18 },
    { cod: 1810, nome: "Oliveira de Frades", distrito: 18 },
    { cod: 1811, nome: "Penalva do Castelo", distrito: 18 },
    { cod: 1812, nome: "Penedono", distrito: 18 },
    { cod: 1813, nome: "Resende", distrito: 18 },
    { cod: 1814, nome: "Santa Comba Dão", distrito: 18 },
    {
      cod: 1815,
      nome: "São João da Pesqueira",
      distrito: 18,
    },
    { cod: 1816, nome: "São Pedro do Sul", distrito: 18 },
    { cod: 1817, nome: "Sátão", distrito: 18 },
    { cod: 1818, nome: "Sernancelhe", distrito: 18 },
    { cod: 1819, nome: "Tabuaço", distrito: 18 },
    { cod: 1820, nome: "Tarouca", distrito: 18 },
    { cod: 1821, nome: "Tondela", distrito: 18 },
    { cod: 1822, nome: "Vila Nova de Paiva", distrito: 18 },
    { cod: 1823, nome: "Viseu", distrito: 18 },
    { cod: 1824, nome: "Vouzela", distrito: 18 },
  ],
};
