module.exports = [
  { cod: 1, abrev: "AVR", nome: "Aveiro" },
  { cod: 2, abrev: "BEJ", nome: "Beja" },
  { cod: 3, abrev: "BRA", nome: "Braga" },
  { cod: 4, abrev: "BRG", nome: "Bragança" },
  { cod: 5, abrev: "CAB", nome: "Castelo Branco" },
  { cod: 6, abrev: "CBR", nome: "Coimbra" },
  { cod: 7, abrev: "EVR", nome: "Évora" },
  { cod: 8, abrev: "FAR", nome: "Faro" },
  { cod: 9, abrev: "GUA", nome: "Guarda" },
  { cod: 10, abrev: "LRA", nome: "Leiria" },
  { cod: 11, abrev: "LSB", nome: "Lisboa" },
  { cod: 12, abrev: "PTG", nome: "Portalegre" },
  { cod: 13, abrev: "POR", nome: "Porto" },
  { cod: 14, abrev: "STR", nome: "Santarém" },
  { cod: 15, abrev: "SET", nome: "Setubal" },
  { cod: 16, abrev: "VCT", nome: "Viana do Castelo" },
  { cod: 17, abrev: "VRL", nome: "Vila Real" },
  { cod: 18, abrev: "VIS", nome: "Viseu" },
  { cod: 31, abrev: "MAD", nome: "Ilha da Madeira" },
  { cod: 32, abrev: "PST", nome: "Ilha de Porto Santo" },
  { cod: 41, abrev: "SMA", nome: "Ilha Santa Maria" },
  { cod: 42, abrev: "SMI", nome: "Ilha São Miguel" },
  { cod: 43, abrev: "TER", nome: "Ilha Terceira" },
  { cod: 44, abrev: "GRA", nome: "Ilha da Graciosa" },
  { cod: 45, abrev: "SJG", nome: "Ilha São Jorge" },
  { cod: 46, abrev: "PIC", nome: "Ilha do Pico" },
  { cod: 47, abrev: "FAI", nome: "Ilha do Faial" },
  { cod: 48, abrev: "FLO", nome: "Ilha das Flores" },
  { cod: 49, abrev: "COR", nome: "Ilha do Corvo" },
];
