name: Build Docker Image CI

on: workflow_dispatch
# on:
#   push:
#     branches: [ "main" ]
#     branches: [ "ci-actions" ]
# pull_request:
#   branches: [ "main" ]

# workflow global variables
env:
  REG_URL: reg.gabtec.pt/oss/
  PROJ_NAME: freeapis
  PROJ_VERSION: v1.0.10

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REG_URL }}
          username: ${{ secrets.REG_USER }}
          password: ${{ secrets.REG_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.REG_URL }}/${{ PROJ_NAME }}:latest, ${{ env.REG_URL }}/${{ PROJ_NAME }}:${{ PROJ_VERSION }}
          # tags: $REG_URL/$PROJ_NAME:latest, $REG_URL/$PROJ_NAME:${{ github.sha }}
