name: Build Docker Image CI

on:
  workflow_dispatch:
  push:
    #     branches: [ "main" ]
    branches: ['main', 'ci-actions']
    paths-ignore:
      - '**/README.md' # updates on docs won't build container images
  # pull_request:
  #   branches: [ "main" ]

# workflow global variables
env:
  REG_URL: reg.gabtec.pt/oss
  PROJ_NAME: freeapis
  # PROJ_VERSION: v1.1.0
  IS_ON_MAIN: ${{ github.ref == 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get version from package.json
        id: get-version
        run: echo "current-version=$(cat package.json| grep version | cut -f 2 -d ":" | sed 's/[", ]//g')" >> "$GITHUB_OUTPUT"

      - name: Print version in var
        run: echo 'building v${{ steps.get-version.outputs.current-version }}'

      - name: Set up QEMU for Multi-Platform image build
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx for Multi-Platform image build
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REG_URL }}
          username: ${{ secrets.REG_USER }}
          password: ${{ secrets.REG_PASS }}
      - name: Build and push (if on main branch)
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ env.IS_ON_MAIN }}
          tags: ${{ env.REG_URL }}/${{ env.PROJ_NAME }}:latest, ${{ env.REG_URL }}/${{ env.PROJ_NAME }}:v${{ steps.get-version.outputs.current-version }}
          # tags: ${{ env.REG_URL }}/${{ env.PROJ_NAME }}:latest, ${{ env.REG_URL }}/${{ env.PROJ_NAME }}:${{ env.PROJ_VERSION }}
          # tags: $REG_URL/$PROJ_NAME:latest, $REG_URL/$PROJ_NAME:${{ github.sha }}
